language: node_js
node_js:
  - "10.16"

branches:
  only:
    - master
    
cache:
  directories:
    - ./node_modules

before_script:
  - npm install -g @angular/cli
 
install:
  - npm install

script:
  - ng build --prod

notifications:
  email:
    recipients:
      - luka.krnjaic@gmail.com
    on_failure: always
    on_success: always
T
